services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: Admin_User
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
# We are using these ports above in case someone is running locally and already has "postgres" installed
# so there won't be any kind of conflict.
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db: